### ISSUE TITLE
`blitz new` docs missing `--js` toggle

### ISSUE THREAD

**Issue by Weilbyte** [blitz-js/blitzjs.com#224] opened 2020-10-12 22:55 UTC
https://blitzjs.com/docs/cli-new is missing `--js` in the options. Adding it there would be nice.

**Comment by flybayer** [comment] 2020-10-12 23:11
@Weilbyte it's because everything isn't fully working for that yet 😬

**Comment by Weilbyte** [comment] 2020-10-12 23:17
Ah, I see.

**Comment by flybayer** [comment] 2021-01-08 21:33
Duplicate of #118

**Closed by flybayer** 2021-01-08 21:33 UTC
Labels: status/triage
